version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - noctx

  settings:
    errcheck:
      check-type-assertions: true

  exclusions:
    paths:
      - internal/db
